### ISSUE TITLE
Multi-image correlation modelling inference?

### ISSUE THREAD

**Issue by vishaal27** [X-PLUG/mPLUG-Owl#1]
Thank you for the amazing work and releasing such concise code. I had a question about how to do model inference with multi-image inputs. Expanding on your provided inference code, something like this comes to mind:

```python
# We use a human/AI template to organize the context as a multi-turn conversation.
# <image> denotes an image placehold.
prompts = [
'''The following is a conversation between a curious human and AI assistant. The assistant gives helpful, detailed, and polite answers to the user's questions.
Human: <image>
Human: <image>
Human: Is the colour of the animal in the first image the same as the second image?
AI: ''']

# The image paths should be placed in the image_list and kept in the same order as in the prompts.
# We support urls, local file paths and base64 string. You can custom the pre-process of images by modifying the mplug_owl.modeling_mplug_owl.ImageProcessor
image_list = ['https://xxx.com/image_1.jpg', 'https://xxx.com/image_2.jpg',]
```
Could you please confirm if this is the right way to do multi-image inference with the model? 
Thanks!

**Comment by vishaal27** [comment]
Great, thanks for the response!

**Comment by MAGAer13** [comment]
Hi, just for noticing that we have corrected the link for downloading the instruction fine-tuned checkpoint.

**Comment by Deep1994** [comment]
> Thank you for your question. Yes, we do use the same format as yours when testing the cross-image understanding ability of our models. BTW, this is an emergent ability, as we do not use any multi-image data during training. Therefore, we believe that exploring formats that can help models better understand multiple images could be beneficial and worth further investigation. Thank you for your interest in our work.

hi, I want to know if this template can also be modified for in-context learning?
