### ISSUE TITLE
video_inference problem

### ISSUE THREAD

**Issue by BruceChen15** [X-PLUG/mPLUG-Owl#100]
Hi,
First of all, thank you for providing such amazing works. But when I trying to inference video inference code that you provided.
I got these error. Can you figure it out?
thx
![image](https://github.com/X-PLUG/mPLUG-Owl/assets/105723918/1acd3dd1-8b1c-44e3-96e8-cf008305c6a8)

**Comment by MAGAer13** [comment]
You can put the model on the GPU.

**Comment by BruceChen15** [comment]
Hi, do you mean that I can revise the code at line 33,34 like below?
Or I just run the command CUDA_VISIBLE_DEVICES=1 python inference_video.py?
thx
![image](https://github.com/X-PLUG/mPLUG-Owl/assets/105723918/0f149939-eaf2-4553-866d-c05fe8b1c6fb)

**Comment by MAGAer13** [comment]
```python
model = MplugOwlForConditionalGeneration.from_pretrained(
   pretrained_ckpt,
   torch_dtype=torch.bfloat16,
   device_map={'': 0},
)
```

You can modify like this, and try run with `CUDA_VISIBLE_DEVICES=1 python inference_video.py`

**Comment by BruceChen15** [comment]
thank you. problem sloved.

**Comment by MAGAer13** [comment]
> thank you. problem sloved.

Did you observe the nan phenomenon?

**Comment by BruceChen15** [comment]
Yes...
I find out that x.half() would become nan after some iterations.
![image](https://github.com/X-PLUG/mPLUG-Owl/assets/105723918/ad07e11b-af8a-4132-bde1-a4626e67d288)
![image](https://github.com/X-PLUG/mPLUG-Owl/assets/105723918/cf59eb6d-79ff-4965-848e-c9cd2d1857a1)

**Comment by MAGAer13** [comment]
What about `bfloat16`?

**Comment by MAGAer13** [comment]
Do you test it on inference?

**Comment by yinkangning0124** [comment]
Have you solve this problem? I also got the NAN problem when running video_inference

**Comment by BruceChen15** [comment]
> Have you solve this problem? I also got the NAN problem when running video_inference

Not yet

**Comment by MAGAer13** [comment]
See #101 .
