### ISSUE TITLE
Video training process

### ISSUE THREAD

**Issue by wang9danzuishuai** [X-PLUG/mPLUG-Owl#103]
Hi! Thank you for your great work.
Recently we are preparing for the video Q&A dataset. We want to use mPLUG-Owl to do some experiments.
So will there be a release of video training code and dataset instruction like the image-version?
Thank you very much! :D

**Comment by mfishzhang** [comment]
I have the same request, only image type input is supported in the current training pipeline code, but I want to test training this model with data containing video.
Thank you very much! I will be very grateful if you can provide code！

**Comment by fanbooo** [comment]
same request

**Comment by MAGAer13** [comment]
No, we do not use any video-instruction data. The video training code can be modified from image version.
