### ISSUE TITLE
The implementation is error in forward method

### ISSUE THREAD

**Issue by zipzou** [X-PLUG/mPLUG-Owl#107]
See line at: https://github.com/X-PLUG/mPLUG-Owl/blob/main/mplug_owl/modeling_mplug_owl.py#L1448C9-L1448C25

In the `forward` method of the `MplugOwlForConditionalGeneration` model, there are three mask arguments are optional: `non_padding_mask`, `non_media_mask`, `prompt_mask`. These masks will be used to get loss mask, but your code has no additional process while them passed with `None`. And your `generate` method has been rewritten without invoking `forward`, thus this error would not happened.

<img width="633" alt="image" src="https://github.com/X-PLUG/mPLUG-Owl/assets/13446458/3aaed772-7563-4f9c-8f1e-6ed2664b4a22">

Like this, if masks were `None`, this method raises `None Exception` directly.

**Comment by MAGAer13** [comment]
During training, these masks would not be None. See the part of dataset.
