### ISSUE TITLE
Could not download the weight

### ISSUE THREAD

**Issue by chenyd0763** [X-PLUG/mPLUG-Owl#11]
I appreciate the great work!! But when I tried to deploy the model in my local machine, there is no response after I clicked the download button for the weight. Is it possible to store the weight in different platform?

**Comment by MAGAer13** [comment]
Hi, try use wget to download it.
`wget "http://mm-chatgpt.oss-cn-zhangjiakou.aliyuncs.com/mplug_owl_demo/released_checkpoint/instruction_tuned.pth"`

For pretraining checkpoint, replace `instruction_tuned.pth` with `pretrain.pth`

**Comment by MAGAer13** [comment]
Hi, all! Just quick notice about our latest version of mPLUG-Owl which remove the dependency of apex! And the checkpoints are hosting on huggingface model hub!
