### ISSUE TITLE
train_it.sh do not match the paper

### ISSUE THREAD

**Issue by linhaojia13** [X-PLUG/mPLUG-Owl#110]
Specifically, in train_it.sh, it shows `micro_batch_size=4`, `nproc_per_node=8`, `nnodes=1`, and `gradient_accumulation_steps=1`, which results in a `global_batch_size` of 32, rather than the 256 mentioned in the paper. 

To replicate the results from the paper, should I adjust `gradient_accumulation_steps` and `micro_batch_size` to align with the `global_batch_size` mentioned in the paper, or should I directly use the train_it.sh script that you have released?

**Comment by MAGAer13** [comment]
We just give a sample of code how it works.

**Comment by Zhoues** [comment]
> We just give a sample of code how it works.

Sorry to bother you, where can I get this sample?

**Comment by Zhoues** [comment]
> Specifically, in train_it.sh, it shows `micro_batch_size=4`, `nproc_per_node=8`, `nnodes=1`, and `gradient_accumulation_steps=1`, which results in a `global_batch_size` of 32, rather than the 256 mentioned in the paper.
> 
> To replicate the results from the paper, should I adjust `gradient_accumulation_steps` and `micro_batch_size` to align with the `global_batch_size` mentioned in the paper, or should I directly use the train_it.sh script that you have released?

Sorry to bother you，my good friend. Do you understand how it works 😭
