### ISSUE TITLE
How to Prepare the data format in order to Run Inference in Batch?

### ISSUE THREAD

**Issue by FuxiaoLiu** [X-PLUG/mPLUG-Owl#119]
<img width="867" alt="image" src="https://github.com/X-PLUG/mPLUG-Owl/assets/60458715/57c74ca3-5c13-4ac6-93f4-8067b2f054d0">

May I ask how I can prepare the data format for the inference? I want to run them in batch. Thanks!

**Comment by MAGAer13** [comment]
Currently, we only support single instance inference. Noqa on batch inference.
