### ISSUE TITLE
Local Demo doesn't have text input

### ISSUE THREAD

**Issue by FuxiaoLiu** [X-PLUG/mPLUG-Owl#120]
<img width="801" alt="image" src="https://github.com/X-PLUG/mPLUG-Owl/assets/60458715/4f2ef437-ba00-49b6-9110-f385e3e5add1">

The errors are as follows:

_(mplug_owl) bash-4.4$ python -m serve.web_server --base-model /fs/vulcan-projects/semantic_consistency_fuxiao/MSR/mplug_model/lora
install flash-attn first.

The model weights are not tied. Please use the `tie_weights` method before using the `infer_auto_device` function.
/vulcanscratch/fl3es/miniconda3/envs/mplug_owl/lib/python3.10/site-packages/gradio/deprecation.py:43: UserWarning: You have unused kwarg parameters in Chatbot, please remove them: {'elem_classes': None}
  warnings.warn(
/vulcanscratch/fl3es/miniconda3/envs/mplug_owl/lib/python3.10/site-packages/gradio/utils.py:846: UserWarning: Expected 2 arguments for function <function upvote_last_response at 0x7fa4dffd3490>, received 1.
  warnings.warn(
/vulcanscratch/fl3es/miniconda3/envs/mplug_owl/lib/python3.10/site-packages/gradio/utils.py:850: UserWarning: Expected at least 2 arguments for function <function upvote_last_response at 0x7fa4dffd3490>, received 1.
  warnings.warn(
/vulcanscratch/fl3es/miniconda3/envs/mplug_owl/lib/python3.10/site-packages/gradio/utils.py:846: UserWarning: Expected 2 arguments for function <function downvote_last_response at 0x7fa4dffd3520>, received 1.
  warnings.warn(
/vulcanscratch/fl3es/miniconda3/envs/mplug_owl/lib/python3.10/site-packages/gradio/utils.py:850: UserWarning: Expected at least 2 arguments for function <function downvote_last_response at 0x7fa4dffd3520>, received 1.
  warnings.warn(
/vulcanscratch/fl3es/miniconda3/envs/mplug_owl/lib/python3.10/site-packages/gradio/utils.py:846: UserWarning: Expected 2 arguments for function <function flag_last_response at 0x7fa4dffd35b0>, received 1.
  warnings.warn(
/vulcanscratch/fl3es/miniconda3/envs/mplug_owl/lib/python3.10/site-packages/gradio/utils.py:850: UserWarning: Expected at least 2 arguments for function <function flag_last_response at 0x7fa4dffd35b0>, received 1.
  warnings.warn(
Running on local URL:  http://0.0.0.0:7860
Running on public URL: https://5b5a33d941a7ab72e5.gradio.live

This share link expires in 72 hours. For free permanent hosting and GPU upgrades (NEW!), check out Spaces: https://huggingface.co/spaces
Task exception was never retrieved
future: <Task finished name='u8mf7035okk_8' coro=<Queue.process_events() done, defined at /vulcanscratch/fl3es/miniconda3/envs/mplug_owl/lib/python3.10/site-packages/gradio/queueing.py:343> exception=1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'fn_index': 8, 'data': [...on_hash': 'u8mf7035okk'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.1/v/missing>
Traceback (most recent call last):
  File "/vulcanscratch/fl3es/miniconda3/envs/mplug_owl/lib/python3.10/site-packages/gradio/queueing.py", line 347, in process_events
    client_awake = await self.gather_event_data(event)
  File "/vulcanscratch/fl3es/miniconda3/envs/mplug_owl/lib/python3.10/site-packages/gradio/queueing.py", line 220, in gather_event_data
    data, client_awake = await self.get_message(event, timeout=receive_timeout)
  File "/vulcanscratch/fl3es/miniconda3/envs/mplug_owl/lib/python3.10/site-packages/gradio/queueing.py", line 456, in get_message
    return PredictBody(**data), True
  File "/vulcanscratch/fl3es/miniconda3/envs/mplug_owl/lib/python3.10/site-packages/pydantic/main.py", line 159, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'fn_index': 8, 'data': [...on_hash': 'u8mf7035okk'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.1/v/missing_

**Comment by Zhoues** [comment]
> <img alt="image" width="801" src="https://user-images.githubusercontent.com/60458715/259282694-4f2ef437-ba00-49b6-9110-f385e3e5add1.png">
> The errors are as follows:
> 
> _(mplug_owl) bash-4.4$ python -m serve.web_server --base-model /fs/vulcan-projects/semantic_consistency_fuxiao/MSR/mplug_model/lora install flash-attn first.
> 
> The model weights are not tied. Please use the `tie_weights` method before using the `infer_auto_device` function. /vulcanscratch/fl3es/miniconda3/envs/mplug_owl/lib/python3.10/site-packages/gradio/deprecation.py:43: UserWarning: You have unused kwarg parameters in Chatbot, please remove them: {'elem_classes': None} warnings.warn( /vulcanscratch/fl3es/miniconda3/envs/mplug_owl/lib/python3.10/site-packages/gradio/utils.py:846: UserWarning: Expected 2 arguments for function <function upvote_last_response at 0x7fa4dffd3490>, received 1. warnings.warn( /vulcanscratch/fl3es/miniconda3/envs/mplug_owl/lib/python3.10/site-packages/gradio/utils.py:850: UserWarning: Expected at least 2 arguments for function <function upvote_last_response at 0x7fa4dffd3490>, received 1. warnings.warn( /vulcanscratch/fl3es/miniconda3/envs/mplug_owl/lib/python3.10/site-packages/gradio/utils.py:846: UserWarning: Expected 2 arguments for function <function downvote_last_response at 0x7fa4dffd3520>, received 1. warnings.warn( /vulcanscratch/fl3es/miniconda3/envs/mplug_owl/lib/python3.10/site-packages/gradio/utils.py:850: UserWarning: Expected at least 2 arguments for function <function downvote_last_response at 0x7fa4dffd3520>, received 1. warnings.warn( /vulcanscratch/fl3es/miniconda3/envs/mplug_owl/lib/python3.10/site-packages/gradio/utils.py:846: UserWarning: Expected 2 arguments for function <function flag_last_response at 0x7fa4dffd35b0>, received 1. warnings.warn( /vulcanscratch/fl3es/miniconda3/envs/mplug_owl/lib/python3.10/site-packages/gradio/utils.py:850: UserWarning: Expected at least 2 arguments for function <function flag_last_response at 0x7fa4dffd35b0>, received 1. warnings.warn( Running on local URL: http://0.0.0.0:7860 Running on public URL: https://5b5a33d941a7ab72e5.gradio.live
> 
> This share link expires in 72 hours. For free permanent hosting and GPU upgrades (NEW!), check out Spaces: https://huggingface.co/spaces Task exception was never retrieved future: <Task finished name='u8mf7035okk_8' coro=<Queue.process_events() done, defined at /vulcanscratch/fl3es/miniconda3/envs/mplug_owl/lib/python3.10/site-packages/gradio/queueing.py:343> exception=1 validation error for PredictBody event_id Field required [type=missing, input_value={'fn_index': 8, 'data': [...on_hash': 'u8mf7035okk'}, input_type=dict] For further information visit https://errors.pydantic.dev/2.1/v/missing> Traceback (most recent call last): File "/vulcanscratch/fl3es/miniconda3/envs/mplug_owl/lib/python3.10/site-packages/gradio/queueing.py", line 347, in process_events client_awake = await self.gather_event_data(event) File "/vulcanscratch/fl3es/miniconda3/envs/mplug_owl/lib/python3.10/site-packages/gradio/queueing.py", line 220, in gather_event_data data, client_awake = await self.get_message(event, timeout=receive_timeout) File "/vulcanscratch/fl3es/miniconda3/envs/mplug_owl/lib/python3.10/site-packages/gradio/queueing.py", line 456, in get_message return PredictBody(**data), True File "/vulcanscratch/fl3es/miniconda3/envs/mplug_owl/lib/python3.10/site-packages/pydantic/main.py", line 159, in **init** **pydantic_self**.**pydantic_validator**.validate_python(data, self_instance=**pydantic_self**) pydantic_core._pydantic_core.ValidationError: 1 validation error for PredictBody event_id Field required [type=missing, input_value={'fn_index': 8, 'data': [...on_hash': 'u8mf7035okk'}, input_type=dict] For further information visit https://errors.pydantic.dev/2.1/v/missing_

Can you tell me how you solved it in a simple way 😭 ?

**Comment by wufan-tb** [comment]
I faced this problem too, do you soved this at last?

**Comment by buaachen1993** [comment]
I faced the same problem

**Comment by buaachen1993** [comment]
I have solved this issue. You need to modify the 'visible' attribute of the corresponding module in the web_server.py file to True.
