### ISSUE TITLE
Code for Video Retrieval

### ISSUE THREAD

**Issue by Hritikbansal** [X-PLUG/mPLUG-Owl#121]
Hi @MAGAer13 @LukeForeverYoung @xuguohai ,
 
Can you point me to the video-text retrieval code in the repo? If there is no direct code for it, can you point me to the exact text and video embeddings that can be used for calculating the text-video similarity?

This is a followup to an issue in the mPLUG-2 repo (https://github.com/X-PLUG/mPLUG-2/issues/5).

**Comment by MAGAer13** [comment]
Please refer to https://github.com/X-PLUG/mPLUG/blob/main/models/model_retrieval_mplug.py which is similar for video-text retrieval.
