### ISSUE TITLE
What is gradio version?

### ISSUE THREAD

**Issue by tuong-lq** [X-PLUG/mPLUG-Owl#126]
Please, give me the version of gradio! I can not run Web demo.

**Comment by FuxiaoLiu** [comment]
> Please, give me the version of gradio! I can not run Web demo.

3.31.0 works for me or you can check this [link](https://github.com/FuxiaoLiu/LRV-Instruction/tree/main/utils).

**Comment by tuong-lq** [comment]
Thanks you @FuxiaoLiu . It works fine
