### ISSUE TITLE
Pydantic version problem and local demo problem.

### ISSUE THREAD

**Issue by Creator404** [X-PLUG/mPLUG-Owl#127]
I have the same problem like https://github.com/adw0rd/instagrapi/issues/1435

Just looks like:
Field required [type=missing, input_value={'id': '52761857721', 'pk': '52761857721'}, input_type=dict]
For further information visit https://errors.pydantic.dev/2.0.1/v/missing
profile_pic_url
Field required [type=missing, input_value={'id': '52761857721', 'pk': '52761857721'}, input_type=dict]
For further information visit https://errors.pydantic.dev/2.0.1/v/missing
profile_pic_url_hd
Field required [type=missing, input_value={'id': '52761857721', 'pk': '52761857721'}, input_type=dict]
For further information visit https://errors.pydantic.dev/2.0.1/v/missing
is_private
Field required [type=missing, input_value={'id': '52761857721', 'pk': '52761857721'}, input_type=dict]
For further information visit https://errors.pydantic.dev/2.0.1/v/missing

I follow the instructions that revoke the pydantic version from 2.0.x to 1.10.9, then the project can work properly.

plz insert into requirements.txt:
pydantic==1.10.9

Also, in file https://github.com/X-PLUG/mPLUG-Owl/blob/main/serve/web_server.py, in function build_demo(), chatbot, textbox and some other components are set invisible(the arg visible is set as False). Please update the code and set them True, that will help a lot(I have seen the other users had the same problem).

**Comment by MAGAer13** [comment]
You can use the latest gradio, like 3.31.0.
