### ISSUE TITLE
Fine-tune customized video dataset based on mPLUG_owl.

### ISSUE THREAD

**Issue by hcwei13** [X-PLUG/mPLUG-Owl#130]
Thank you for the outstanding work of the team. I hope to fine-tune customized video dataset based on mPLUG_owl. I attempted to modify the image-based fine-tuning code, but encountered an error: RuntimeError: "conv_depthwise3d" not implemented for 'BFloat16'. I suspect this might be because the model is initially loaded onto the CPU. I tried changing 'bf16' to False, which resulted in 'video_query_output' containing NaN values. I have also downloaded temporary weights to replace those on the HuggingFace repository, but it had no effect. This issue has been bothering me for a while, and I hope you could provide some suggestions. Thanks!

**Comment by hcwei13** [comment]
@MAGAer13

**Comment by MAGAer13** [comment]
You can convert the input of depth-conv3d as fp16, then convert it back

**Comment by zhouwei5113** [comment]
> Thank you for the outstanding work of the team. I hope to fine-tune customized video dataset based on mPLUG_owl. I attempted to modify the image-based fine-tuning code, but encountered an error: RuntimeError: "conv_depthwise3d" not implemented for 'BFloat16'. I suspect this might be because the model is initially loaded onto the CPU. I tried changing 'bf16' to False, which resulted in 'video_query_output' containing NaN values. I have also downloaded temporary weights to replace those on the HuggingFace repository, but it had no effect. This issue has been bothering me for a while, and I hope you could provide some suggestions. Thanks!

Did you solve the issue？

**Comment by Hritikbansal** [comment]
@MAGAer13 I had an impression that https://github.com/X-PLUG/mPLUG-Owl/blob/main/mplug_owl_video/modeling_mplug_owl.py#L214 already fixes this issue since you are manually changing the bfloat to half here but the issue still persists. 

@hcwei13 @zhouwei5113 is this issue fixed for you or have you found a work around?

**Comment by hcwei13** [comment]
Unfortunately, this problem still exists. @Hritikbansal @zhouwei5113 @LukeForeverYoung @MAGAer13

**Comment by Hritikbansal** [comment]
Hi @hcwei13 , I fixed the problem as follows:

```
x = self.down_proj(x)
_device = x.device
self = self.to('cpu') # hack: cpu offloading since bfloat16 on gpu gives error with conv_depthwise3d but works with cpu
x = x.to('cpu')
x = self.conv(x)
self = self.to(_device)
x = x.to(_device)
x = self.activation_func(x)
```

my change may have some latency related repercussions since I perform cpu offloading but it makes the code work on GPU/multi-GPU setup.

**Comment by hcwei13** [comment]
It works!!! thanks!!! @Hritikbansal
