### ISSUE TITLE
TypeError in loading the model

### ISSUE THREAD

**Issue by srivivtcs** [X-PLUG/mPLUG-Owl#132]
Hi, I am trying to load the model in HuggingFace style. The following line in the code is giving the error:

model = MplugOwlForConditionalGeneration.from_pretrained(
    pretrained_ckpt,
    torch_dtype=torch.bfloat16,
)

The error I am getting is: TypeError: Object of type method is not JSON serializable 

I have tried loading the model from a local repository as well. But no luck so far.

**Comment by MAGAer13** [comment]
One things you can try is to install the transformer package with version 4.29.0. It may help.

**Comment by srivivtcs** [comment]
It worked, thanks!

**Comment by 18445864529** [comment]
So what is the core cause of this? It is not a good solution to downgrade to an older version of transformers to use the model.

**Comment by admk** [comment]
How I can I get it to work in 4.34.1? I have other models in the same project that can only work with recent versions of `transformers`.

**Comment by 18445864529** [comment]
> How I can I get it to work in 4.34.1? I have other models in the same project that can only work with recent versions of `transformers`.

when hf tries to get string representations of the model, there's a module that cannot be converted to string. The fastest but dirty way is to modify the source code of hf where gives u the error, adding a try-except. If the module cannot be stringtized just set it to a certain string instead.

**Comment by admk** [comment]
Thanks, I used
```python
from transformers.configuration_utils import PretrainedConfig
from mplug_owl.configuration_mplug_owl import MplugOwlConfig

MplugOwlConfig.to_json_string = lambda *args, **kwargs: ''
```
as a temporary hack for loading.
