### ISSUE TITLE
TypeError: not a string

### ISSUE THREAD

**Issue by neverstoplearn** [X-PLUG/mPLUG-Owl#141]
and also if this repo could fintune the multilange model? I got this error:
TypeError: not a string
The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization.
The tokenizer class you load from this checkpoint is 'BloomTokenizerFast'.
The class this function is called from is 'MplugOwlTokenizer'.

**Comment by neverstoplearn** [comment]
{
"image": ["images/33010001-2022_10_20_09_59_56_HANG_CLOTHES_OUT.jpg"],
"text": "以下是一个好奇的人类和人工智能助手之间的对话。助理对用户的问题提供有用、详细且礼貌的回答。\nHuman: <image>\nHuman: 这张图片里有哪些违规事件类型？\nAI: 这张图片的违规事件类型有道路不洁",
"task_type": "gpt4instruct_sft"
}  
And  I also want to know is this right?

**Comment by MAGAer13** [comment]
You can directly use BloomTokenizerFast instead of MplugOwlTokenizer. And your data format is correct.

**Comment by TonyAlbertWan** [comment]
hello! have u solve the problem?
By directily using BloomTokenizerFast, do i have to change the code except line 141 from `train.py`:
`    tokenizer = BloomTokenizerFast.from_pretrained(args.pretrained_ckpt)
    # tokenizer = MplugOwlTokenizer.from_pretrained(args.pretrained_ckpt)`
is there other issues should i concern?
thanks!
