### ISSUE TITLE
curious about Alpaca and Vicuna datasets used in the training.

### ISSUE THREAD

**Issue by Maxlinn** [X-PLUG/mPLUG-Owl#15]
hi to the team, thanks for your hard work and mPLUG-Owl demostrated great performance!

during reading the paper, i found that in "4.1 Experimental Setup/Data and Training Details.", it said "we gather pure text instruction data from three distinct sources: 102k data from the Alpaca [Taori et al., 2023], 90k from the Vicuna [Vicuna, 2023], and 50k from the Baize [Xu et al., 2023a]."

however, to my knowledge 
- the [alpaca](https://github.com/tatsu-lab/stanford_alpaca) dataset only has 52k examples 
- [vicuna](https://github.com/lm-sys/FastChat) has not released their dataset yet due to some concern. 

would you mind sharing more information about the datasets? thanks a lot!

**Comment by MAGAer13** [comment]
Hi, thanks for having interest in our work.

For the dataset information:
- We have the typo in the number of dataset from alpaca, the actual number is 52k as you stated.
- For Vicuna, you can refer to its issue where people shares the ShareGPT dataset on huggingface. Used as your own risk.
