### ISSUE TITLE
Conflicting requirements

### ISSUE THREAD

**Issue by joehoover** [X-PLUG/mPLUG-Owl#18]
There are conflicts between the dependencies specified in the README and `env.yaml`.

In the README, `torchvision` is not specified and `torch` is pinned at `1.13.1`. Further, in `env.yaml` `peft` is not listed as a dependency.

```
PyTorch=1.13.1 (1.13.1 is required by the peft)
```

However, when I tried to run the demo like:

```
python -m server_mplug.owl_demo --debug --port 6363 --checkpoint_path 'your checkpoint path' --tokenizer_path 'your tokenizer path'
```

I got an import error for `torchvision`.

I then referred to `env.yaml` for dependencies, but there torch is pinned at `1.12.1`

```
  - pytorch=1.12.1=py3.10_cuda11.3_cudnn8.3.2_0
```

This conflicts with the version specified in the README.

**Comment by joehoover** [comment]
Wow, thanks for the fast response!

I might just wait for the next version. Do you have an ETA for that?

Unfortunately, I ran into another issue with dependency conflicts. 

`torchvision==0.13.1` is not compatible with `torch==1.13.1`. 

What version of `torchvision` would you recommend?

**Comment by MAGAer13** [comment]
You might use the following script here to install the torch and torchvision for your reference.
`conda install pytorch==1.13.1 torchvision==0.14.1 torchaudio==0.13.1 pytorch-cuda=11.7 -c pytorch -c nvidia`

For the next version, we aim to natively support the huggingface library! Besides, we are working on multi-lingual support of that. We would release it as soon as the training is done.

**Comment by MAGAer13** [comment]
If you have any further question or need help, we can set up a slack / discord channel to help you. 😊

**Comment by MAGAer13** [comment]
> Wow, thanks for the fast response!
> 
> I might just wait for the next version. Do you have an ETA for that?
> 
> Unfortunately, I ran into another issue with dependency conflicts.
> 
> `torchvision==0.13.1` is not compatible with `torch==1.13.1`.
> 
> What version of `torchvision` would you recommend?

Hi, just quick notice for the next version have been released with much easier usage!
