### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by thiner** [X-PLUG/mPLUG-Owl#2]
I tried to prepare environment with `conda env create -f env.yaml`, but failed. The error message as below:

> Pip subprocess error:
ERROR: Ignored the following versions that require a different python version: 2.10.1 Requires-Python <3; 2.11.0 Requires-Python <3; 2.11.1 Requires-Python <3; 2.4.0 Requires-Python <3; 2.4.1 Requires-Python <3; 2.4.2 Requires-Python <3; 2.4.3 Requires-Python <3; 2.4.4 Requires-Python <3; 2.5.0 Requires-Python <3; 2.5.1 Requires-Python <3; 2.5.2 Requires-Python <3; 2.6.0 Requires-Python <3; 2.6.1 Requires-Python <3; 2.6.2 Requires-Python <3; 2.7.0 Requires-Python <3; 2.7.2 Requires-Python <3; 2.8.0 Requires-Python <3; 2.8.1 Requires-Python <3; 2.8.2 Requires-Python <3; 2.8.3 Requires-Python <3; 2.8.4 Requires-Python <3; 2.8.5 Requires-Python <3; 2.8.6 Requires-Python <3; 2.8.7 Requires-Python <3; 2.9.2 Requires-Python <3
ERROR: Could not find a version that satisfies the requirement apex==0.1 (from versions: 0.9.8dev.linux-i686, 0.9.8.dev0, 0.9.8a0.dev0, 0.9.9.dev0, 0.9.10.dev0)
ERROR: No matching distribution found for apex==0.1

>failed

>CondaEnvException: Pip failed

**Comment by vishaal27** [comment]
Do you install apex from source on A100s? Seems like the installation is not as straightforward for them.

**Comment by MAGAer13** [comment]
We recommand to install apex from the source. [Apex](https://github.com/NVIDIA/apex).

```
git clone https://github.com/NVIDIA/apex
cd apex
pip install -v --disable-pip-version-check --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" ./
```

**Comment by LukeForeverYoung** [comment]
Our repository now includes an Apex copy and installation guidelines, which have been validated for installation in V100 and A100 with PyTorch 1.13.1+cu117. Please refer to the repository for more information.

**Comment by thiner** [comment]
Thanks for your updates. But maybe you forgot to push the `apex_22.01_pp` code?

**Comment by MAGAer13** [comment]
We have updated it. By the way, we are planning to remove the reliance of apex in the next version. Stay Tuned.

**Comment by thiner** [comment]
Installation failed again.
I updated the env.yaml file, update the pytorch version to 1.13.1 as you mentioned above. But it ran into error prompting plenty of lib version imcompatible issues. Can you generat a workable `environment.yml` file by `conda env export --from-history | findstr -v "prefix" > environment.yml` ?

**Comment by cnxupupup** [comment]
Does the Apex installation of your project support 3090 or TITAN RTX？because there are some problems encountered in the installation
