### ISSUE TITLE
No module named 'mplug_owl2.model.multiway

### ISSUE THREAD

**Issue by YHWmz** [X-PLUG/mPLUG-Owl#202]
Hello,
I encountered the error "No module named 'mplug_owl2.model.multiway" while trying to run the Quick Start Code 

This issue arises from mPLUG-Owl2/mplug_owl2/model/modeling_llama2.py at line 18, 
```
from .multiway import MultiwayNetwork
```
However, it seems that the multiway.py file is missing. Could you please advise on how to resolve this issue?

**Comment by LukeForeverYoung** [comment]
Sorry for files missing due to an incomplete commit. We re-commit these filesin the latest commit.
