### ISSUE TITLE
maybe bug in processing_mplugowl3.py ?

### ISSUE THREAD

**Issue by hpy-42** [X-PLUG/mPLUG-Owl#231]
https://huggingface.co/mPLUG/mPLUG-Owl3-7B-240728/blob/main/processing_mplugowl3.py#L232

When `self.image_processor.add_global` set to True, i think `image_token_ptr` should += 1 one more time during the loop... 
```python
for next_text in text_list[1:]:
    text += self.image_processor.cut_prompt_template(img_token='<|image|>', h=cut_shape[image_token_ptr][0], w=cut_shape[image_token_ptr][1])
    text += next_text
    image_token_ptr += 1
    ### ptr to next image
    if self.image_processor.add_global:
        image_token_ptr += 1
message['content'] = text

**Comment by LukeForeverYoung** [comment]
Thank you for pointing this issue. It is a bug and we will fix it soon. In our demo and evaluation, we turn off image cut, so it temporarily does not affect the performance of the model in most scenarios.

**Comment by LukeForeverYoung** [comment]
We fixed this issue and updated the code in Hugging Face and ModelScope. However, we found that because we never trained the model with multi-image input when enabling the image cut, the performance is suboptimal. We will improve this weakness in the next model release.

**Comment by YUANMU227** [comment]
你好，对于mPLUG_Owl3_7B_241101，使用modelscope进行推理依然有相关报错：

from modelscope import AutoConfig, AutoModel, AutoTokenizer
config = AutoConfig.from_pretrained(model_path, trust_remote_code=True)
print(config)
model = AutoModel.from_pretrained(model_path, attn_implementation='flash_attention_2', torch_dtype=torch.bfloat16, trust_remote_code=True)
_ = model.eval().cuda()
tokenizer = AutoTokenizer.from_pretrained(model_path)
processor = model.init_processor(tokenizer)
input_image = Image.open(filename)
inputs = processor(messages, images=[input_image], videos=None)

第二次执行processor(messages, images=[input_image], videos=None)的时候，会有报错：

> inputs = processor(messages, images=[input_image], videos=None)
> File "/nvme1/huggingface/modules/transformers_modules/checkpoint-405-merged/processing_mplugowl3.py", line 226, in __call__
> media_item = medias[image_token_ptr]
> IndexError: list index out of range

对应到modelscope，应如何修改这个bug
