### ISSUE TITLE
NameError: name 'prompts_lists' is not defined

### ISSUE THREAD

**Issue by badarrrr** [X-PLUG/mPLUG-Owl#236]
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
name 'prompts_lists' is not defined
Traceback (most recent call last):
  File "/gemini/code/mPLUG-Owl3/gradio_demo.py", line 135, in chat
    answer = model.chat(
  File "/root/.cache/huggingface/modules/transformers_modules/mPLUG-Owl3-7B-240728/modeling_mplugowl3.py", line 191, in chat
    prompts_lists,
NameError: name 'prompts_lists' is not defined

为什么会报这个错

**Comment by badarrrr** [comment]
有人跑通mPLUG-Owl3的webui吗

**Comment by badarrrr** [comment]
你们的gradio demo真的能跑通吗

**Comment by LukeForeverYoung** [comment]
Sorry, the gradio demo uses the checkpoint we uploaded to the ModelScope. The ```modeling_mplugowl3.py``` file in Huggingface is outdated and we will soon upload the latest version. A workaround is to skip the passing of ```--model_dir```, and it will download the latest checkpoint from ModelScope.

**Comment by badarrrr** [comment]
非常感谢回复！从modelscope重新下载了代码文件之后跑通了！Your work is amazing!
