### ISSUE TITLE
Does mPLUG-Owl3 support no image input?

### ISSUE THREAD

**Issue by aiiph4** [X-PLUG/mPLUG-Owl#238]
I'd like to know if mPLUG-Owl3 supports text-only input. Thank you very much!

**Comment by badarrrr** [comment]
I guess it doesn't work. When I use the gradio demo, an error occurs the first time I enter text. I have to upload an image or video first before I can continue the text conversation.

**Comment by aiiph4** [comment]
I find that simply setting both the images and videos parameters to None in the processor works as expected. Here's how I'm using it:
```inputs = processor(messages, images=None, videos=None)```
