### ISSUE TITLE
How to train mPLUG-Owl3?

### ISSUE THREAD

**Issue by digbangbang** [X-PLUG/mPLUG-Owl#240]
Thanks ur opening the model weights, but how can I train the mPLUG-Owl3 on my own?

**Comment by digbangbang** [comment]
Sorry I have just seen ur TODO list, and hope u will release the training code soon.

**Comment by LukeForeverYoung** [comment]
ms-swift now supports fine-tuning of the mPLUG-Owl3 model. You can follow the documentation available at [this link](https://github.com/modelscope/ms-swift/issues/1969).

If you encounter any issues during training, please feel free to open an issue in either the ms-swift repository or the mPLUG-Owl repository.
