### ISSUE TITLE
How to process video input

### ISSUE THREAD

**Issue by k1tano** [X-PLUG/mPLUG-Owl#32]
I can input video in the Hugging face demo, but I can't find any relevant video data processing in the code. are you only sampling 4 frames of video in the front end and inputting them into the model as images?This is very important to me, please let me know, thanks!

**Comment by MAGAer13** [comment]
Yes, currently we treat video as consecutive pictures as used them as input.

**Comment by xmy0916** [comment]
@MAGAer13 how many frames do you used?

**Comment by shaswati1** [comment]
@k1tano, which huggingface model did you use to input video directly? I found KeyError while trying to load the model in [this link](https://huggingface.co/MAGAer13/mplug-owl-llama-7b-video).
