### ISSUE TITLE
HuggingFace Demo is broken.

### ISSUE THREAD

**Issue by lychees** [X-PLUG/mPLUG-Owl#33]
![image](https://github.com/X-PLUG/mPLUG-Owl/assets/2507027/a51d4b2c-e67d-48d4-94d3-1d2451870d2a)

**Comment by MAGAer13** [comment]
Currently, the model is running under T4 GPU with 16Gb. It might meet out-of-memory error, if too many users have triggered the OOM. We have restarted our demo service and we will update our demo and running on 8 bit precision. Stay tuned.
