### ISSUE TITLE
Weird result？ 

### ISSUE THREAD

**Issue by Zhou2019** [X-PLUG/mPLUG-Owl#34]
![image](https://github.com/X-PLUG/mPLUG-Owl/assets/46622411/bc4c6cd0-7e5c-4ed5-ad21-2aeba1bb39e0)
![image](https://github.com/X-PLUG/mPLUG-Owl/assets/46622411/7dadf7aa-d542-4cfa-87af-252326ed5531)

This is my result. Can you help me what's wrong?
thanks a lot!

**Comment by MAGAer13** [comment]
#33 As we just replied here, we are restarting the service now. I recommand you to try the demo on the [modelscope](https://www.modelscope.cn/studios/damo/mPLUG-Owl/summary) which deploys on V100 machine. We will update the demo on huggingface ASAP

**Comment by MAGAer13** [comment]
Is the weight loaded correctly?
