### ISSUE TITLE
Apex Dependency

### ISSUE THREAD

**Issue by zhongpeixiang** [X-PLUG/mPLUG-Owl#38]
Hi, thank you for sharing your awesome work. I have been trying to run the model locally but the apex dependency and its dependency to specific CUDA versions make the environment setup with older GPUs tricky. Really appreciate if you can remove the apex dependency soon. Thanks!

**Comment by MAGAer13** [comment]
Hi, we will remove the apex dependency in the next week's big version, which refactorize the code and support huggingface trainer! The new library is more easily used. Please stay tuned. 😊

**Comment by MAGAer13** [comment]
Hi, just quick notice about our latest version of mPLUG-Owl which remove the dependency of apex! And it is more easy to use
