### ISSUE TITLE
How to filter the instruction tuning data?

### ISSUE THREAD

**Issue by lovecambi** [X-PLUG/mPLUG-Owl#39]
As the comment text in [config file](https://github.com/X-PLUG/mPLUG-Owl/blob/main/configs/instruction_tuning/v0.yaml), the size of each dataset (# [50997(alpaca), 155562(llava), 53456(quora), 101466(sharegpt)] 361481 ) is different from the original dataset.

Is there any code or script to filter the data?

**Comment by MAGAer13** [comment]
Hi, we did not filter the dataset. Since we held out some data for validation (~1k for each dataset), so the size of each dataset is smaller than the origin one.
