### ISSUE TITLE
Checkpoint links correct?

### ISSUE THREAD

**Issue by vishaal27** [X-PLUG/mPLUG-Owl#4]
Hi, it seems like the checkpoint links for both the pre-trained and the instruction fine-tuned models are the same in the readme. They both point to http://mm-chatgpt.oss-cn-zhangjiakou.aliyuncs.com/mplug_owl_demo/released_checkpoint/pretrained.pth. 
Is this the pre-trained or the instruction fine-tuned model? I'm assuming since this is the checkpoint used in the demo, it is the instruction fine-tuned model?

**Comment by MAGAer13** [comment]
Hi, thanks for having interested in our work. Sorry for the confusing downloading links. We have corrected the link for downloading the instruction fine-tuned checkpoint.
