### ISSUE TITLE
How to use the finetuned model with lora?

### ISSUE THREAD

**Issue by xinghua3632** [X-PLUG/mPLUG-Owl#46]
Interface.py can not load the model that finetuned with lora.

**Comment by lovecambi** [comment]
> Interface.py can not load the model that finetuned with lora.

It needs lora conversion. This codebase didn't full implement it yet.

For a hard-coded workaround, you have to feed this [peft_config](https://github.com/X-PLUG/mPLUG-Owl/blob/main/train.py#L115)
```
peft_config = LoraConfig(
        target_modules=r'.*language_model.*\.(q_proj|v_proj)', inference_mode=False, r=8, lora_alpha=32, lora_dropout=0.05
        )
```
into the function ```get_model``` in ```interface.py```.
