### ISSUE TITLE
dataset problem

### ISSUE THREAD

**Issue by xmy0916** [X-PLUG/mPLUG-Owl#47]
Do you use open source data for the video dataset, or do you organize it yourself?

**Comment by MAGAer13** [comment]
We leverage webvid-10m dataset for video-text pre-training.

**Comment by xmy0916** [comment]
@MAGAer13 video的训练只做了视频文本描述的任务吗，还是加了对比学习呢？数据集也只是用了这个webvid_10m吗？感谢你的回答～

**Comment by MAGAer13** [comment]
Yes, for video-text pre-training we only predict the caption of the video without contrastive learning on webvid-10m only.
