### ISSUE TITLE
Is the training script for the 1st stage provided?

### ISSUE THREAD

**Issue by happycoding1996** [X-PLUG/mPLUG-Owl#49]
Dear authors,

I want to do the 1st stage training with my own caption data, have you provided the training script of that in this repo?

I only find the instructions related to the 2nd training stage in README.md

Thanks for your help!

**Comment by vateye** [comment]
Currently, we do not provide the scripts for pre-training. But you can leverage the provided scripts to pre-train your model. For the most convenient way, you can directly use the checkpoint we provided.

**Comment by MAGAer13** [comment]
Currently, we do not provide the scripts for pre-training. But you can leverage the provided scripts to pre-train your model. For the most convenient way, you can directly use the checkpoint we provided.

**Comment by buaachen1993** [comment]
> Currently, we do not provide the scripts for pre-training. But you can leverage the provided scripts to pre-train your model. For the most convenient way, you can directly use the checkpoint we provided.

So, will there be any plan to release the training script for the first stage?
