### ISSUE TITLE
本地部署的demo启动效果与预期不符？

### ISSUE THREAD

**Issue by hdulbj** [X-PLUG/mPLUG-Owl#50]
通过命令行：python -m server_mplug.owl_demo --debug --port 6363 --checkpoint_path 'your checkpoint path' --tokenizer_path 'your tokenizer path'

但是展示的demo是有缺失的？但我看demo的代码中应该有文本输入及其他的组件的啊
![image](https://github.com/X-PLUG/mPLUG-Owl/assets/22096189/0b2829f6-3880-4046-91a7-766c66ab0196)

**Comment by vateye** [comment]
It seems that the webpage did not load successfully. Try to refresh it.

**Comment by MAGAer13** [comment]
You can refresh the page and try again. Or you can use the provided demo with new version.

**Comment by linhaojia13** [comment]
@hdulbj @MAGAer13 我也遇到了这样的问题，没有文本输入的组件，请问应该如何解决？

**Comment by FuxiaoLiu** [comment]
Do you solve this problem?

**Comment by FuxiaoLiu** [comment]
> @hdulbj @MAGAer13 我也遇到了这样的问题，没有文本输入的组件，请问应该如何解决？

有找到解决办法么？
