### ISSUE TITLE
请问是否可以在readme里写个huggingface的使用说明呢？

### ISSUE THREAD

**Issue by yuqi657** [X-PLUG/mPLUG-Owl#51]
感谢你们的工作，以及发布到huggingface的努力，实在是太棒了。

这个是blip-2写在readme里面的， https://github.com/salesforce/LAVIS/tree/main/projects/blip2 ，可以参考一下最下面。
或者可以附一下huggingface调用mplug-owl的说明吗？我在huggingface里面找了好久没找到呢？只找到了https://huggingface.co/MAGAer13/mplug-owl-llama-7b/discussions ，和 
from transformers import AutoModel
model = AutoModel.from_pretrained("MAGAer13/mplug-owl-llama-7b")，
但是至于如何进行inference，就没找到了。

**Comment by MAGAer13** [comment]
Hi, thanks for your suggestion. We have update the relevant code snippet in 'README.md' for your reference~
