### ISSUE TITLE
Can you transform the v0 checkpoint to the compatible version of new branch?

### ISSUE THREAD

**Issue by lovecambi** [X-PLUG/mPLUG-Owl#52]
I've used the v0 checkpoint for some experiments.

**Comment by LukeForeverYoung** [comment]
If you want to use the v0 checkpoint, you could switch to the v0 branch. The latest model has fixed several issues and removed some dependencies that were difficult to install (such as FusedLayerNorm in Apex), making it incompatible with the v0 checkpoint. Converting the v0 checkpoint to fit the current model may result in precision issues.

**Comment by MAGAer13** [comment]
Besides, for the latest version we follow the same recipe and no more extra data is used.
