### ISSUE TITLE
Train/Validation splits

### ISSUE THREAD

**Issue by zhangliang-04** [X-PLUG/mPLUG-Owl#56]
Dear authors,
Thank you for the great work and open sourcing.
I noticed that you keep about 1k validations for alpaca, llava, quora, and sharegpt [#39](https://github.com/X-PLUG/mPLUG-Owl/issues/39). Since I want to keep the same setting in my experiments, would you mind sharing the splits with me?

**Comment by MAGAer13** [comment]
We randomly shuffle the data with random seed 42 and split into the training and validation split.
