### ISSUE TITLE
How to use Video in the provided interface?

### ISSUE THREAD

**Issue by nullnameno** [X-PLUG/mPLUG-Owl#58]
I am confused about how to pass the video into the model through the interface example you provided? Looking forward to your help，Thanks！

**Comment by MAGAer13** [comment]
Hi, we did not support the video inference in our current codebase, we will support this soon! Now, you can try the demo on huggingface / modelscope for advanced video support, which is trained on Webvid10M.

**Comment by MAGAer13** [comment]
It's a possible way to treat video into several images (e.g. 4 in your case). You need to add 4 "<image>" tokens as the placeholder for video. Otherwise you would only use the first image as the input.

**Comment by nullnameno** [comment]
Thank you very much for your reply! And look forward to the update of mPLUG-owl!

**Comment by MAGAer13** [comment]
We will release the bilingual version of mPLUG-Owl very soon~ We would be happy if you would like to invite more people to use our model.😄
