### ISSUE TITLE
多语言ckpt的问题

### ISSUE THREAD

**Issue by qiuhuiGithub** [X-PLUG/mPLUG-Owl#66]
你好，想问一下，多语言版本的ckpt是从英文版的pre-training ckpt instruct-tuning 得到的，还是从多语言版本的pre-training ckpt instruct-tuning 得到的呢？如果有多语言版本的pre-training ckpt，能否也开源一下呢？

**Comment by MAGAer13** [comment]
The ckpt of multilingual is trained with BloomZ with Chinese and English instruction data. We will release the pre-training checkpoint recently but not very soon.
