### ISSUE TITLE
Can we customize the visual encoder and llm used?

### ISSUE THREAD

**Issue by Akiraxty** [X-PLUG/mPLUG-Owl#69]

**Comment by MAGAer13** [comment]
You are free to replace the visual encoder and LLM. However, once you have replaced one of these, you need to pre-train it first. We recommend you to use the checkpoint we provided.

**Comment by Akiraxty** [comment]
Thank you. It seems that the pre-trained code has not been released yet. I haven't found it.

**Comment by MAGAer13** [comment]
You can refer to the finetuning code for pre-train. The pretrain is similar to the finetuning except for we did not use any prompt.
