### ISSUE TITLE
Will train.py code be released 

### ISSUE THREAD

**Issue by gordonhu608** [X-PLUG/mPLUG-Owl#7]
As title.

**Comment by LukeForeverYoung** [comment]
Yes, the training code will be released soon. The current training pipeline we are using is too complex and difficult to be extended. For this reason, we are in the process of refactoring an open-source version that will be more user-friendly.
Stay tuned!

**Comment by LukeForeverYoung** [comment]
We have just updated the code for instruction tuning. Please refer to the README for more details.
