### ISSUE TITLE
Lower text generation quality with batch size > 1 in mPLUG-owl inference: Seeking insights on possible causes

### ISSUE THREAD

**Issue by pygh0er** [X-PLUG/mPLUG-Owl#85]
Hi,

I have noticed that when performing inference with a batch size greater than 1 using mPLUG-owl, the quality of the generated text is significantly worse compared to when using a batch size of 1. I have thoroughly reviewed the code and couldn't find any potential factors that could cause this issue.

Could you please provide insights into the possible reasons behind this performance difference when using different batch sizes in mPLUG-owl's inference? I would greatly appreciate any suggestions or explanations you can provide.

**Comment by MAGAer13** [comment]
We only support batch_size=1 currently.

**Comment by pygh0er** [comment]
Thanks!
