### ISSUE TITLE
When will release the video generator?

### ISSUE THREAD

**Issue by LinB203** [X-PLUG/mPLUG-Owl#88]
Thanks for your wonderful work!
I wonder know that when will release the video generator like video demo in Huggingface?

**Comment by MAGAer13** [comment]
End of June!

**Comment by overfiter** [comment]
> End of June!

NOW IS THE TIME!!  orz

**Comment by LinB203** [comment]
any news？

**Comment by LinB203** [comment]
> End of June!

any news？

**Comment by LukeForeverYoung** [comment]
> > End of June!
> 
> any news？

tonight !
