### ISSUE TITLE
tokenizer load失败

### ISSUE THREAD

**Issue by dingtine** [X-PLUG/mPLUG-Owl#91]
用MplugOwlTokenizer报：
The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. 
The tokenizer class you load from this checkpoint is 'LlamaTokenizer'. 
The class this function is called from is 'MplugOwlTokenizer'.

改成LlamaTokenizer报：
not a string

**Comment by MAGAer13** [comment]
Try to pull the latest code and the latest checkpoint on huggingface modelhub. The MplugOwlTokenizer is just inherited from LlamaTokenizer.

**Comment by neverstoplearn** [comment]
> Try to pull the latest code and the latest checkpoint on huggingface modelhub. The MplugOwlTokenizer is just inherited from LlamaTokenizer.

IS this repo could fintune mutlilanguage  model?

I got this error:

The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. 
The tokenizer class you load from this checkpoint is 'BloomTokenizerFast'. 
The class this function is called from is 'MplugOwlTokenizer'.

the code and the model are the latest.
thanks.

**Comment by LinB203** [comment]
same question. is it normal?
