### ISSUE TITLE
Video checkpoint available?

### ISSUE THREAD

**Issue by nullnameno** [X-PLUG/mPLUG-Owl#95]
Hello, i notice that 'video checkpoints are available on HuggingFace', but I couldn't find it. May I ask if you have encountered any problems? When is it available?

**Comment by LukeForeverYoung** [comment]
Our server is currently experiencing connectivity issues with HuggingFace, so we're unable to upload the checkpoint to the HF Hub for the time being. We'll upload it as soon as the issues are resolved.

**Comment by nullnameno** [comment]
Thanks! When will it be uploaded to the ModelScope?

**Comment by LinB203** [comment]
OSError: We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like MAGAer13/mplug-owl-llama-7b-video is not the path to a directory containing a file named config.json.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.

**Comment by LinB203** [comment]
> Our server is currently experiencing connectivity issues with HuggingFace, so we're unable to upload the checkpoint to the HF Hub for the time being. We'll upload it as soon as the issues are resolved.

If I run the video code, it will return error as follows. It seem that there is no checkpoint in HuggingFace repo. I wonder know that when will checkpoint be released? Thanks!
`OSError: We couldn't connect to 'https://huggingface.co/' to load this file, couldn't find it in the cached files and it looks like MAGAer13/mplug-owl-llama-7b-video is not the path to a directory containing a file named config.json.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.`

**Comment by MAGAer13** [comment]
Yes, we have not uploaded our checkpoint on HF. We will do this in this week.

**Comment by ceyxasm** [comment]
Does this also affect the local video inference section @MAGAer13 
https://github.com/x-plug/mplug-owl#video-inference

**Comment by MAGAer13** [comment]
> Does this also affect the local video inference section @MAGAer13 https://github.com/x-plug/mplug-owl#video-inference

This means you cannot load the weight, but you can run it without checkpoint, but not recommend.

**Comment by ceyxasm** [comment]
`OSError: It looks like the config file at 'MAGAer13/mplug-owl-llama-7b-video' is not a valid JSON file.`
Okay so. My error looks like this. Any leads

**Comment by MAGAer13** [comment]
> `OSError: It looks like the config file at 'MAGAer13/mplug-owl-llama-7b-video' is not a valid JSON file.` Okay so. My error looks like this. Any leads

You can use the config from `mplug-owl-llama-7b`, the arch is similar. We will upload it tomorrow (I hope so).

**Comment by MAGAer13** [comment]
We did not test for batch inference. You can use the demo on HF for video inference.

**Comment by LinB203** [comment]
> We did not test for batch inference. You can use the demo on HF for video inference.

So if I want to test many sample, I must use a for-loop with batch_size=1? Like this?
`for i in range(100000):
    generated_text = model.forward(one_text, one_video)`

**Comment by MAGAer13** [comment]
> > We did not test for batch inference. You can use the demo on HF for video inference.
> 
> So if I want to test many sample, I must use a for-loop with batch_size=1? Like this? `for i in range(100000): generated_text = model.forward(one_text, one_video)`

Multi-sample inference is not ensured. But for training, it supports batch training. Since the generation procedure is different compared to training.

**Comment by MAGAer13** [comment]
Hi all, the video checkpoint has been released.

**Comment by shaswati1** [comment]
> Hi all, the video checkpoint has been released.

@MAGAer13 , where can I find the video checkpoint (because the one in HF doesn't work)? I could do the inference according to the **video inference instructions** in [this link](https://github.com/X-PLUG/mPLUG-Owl/tree/main/mPLUG-Owl). However, I want to fine-tune this model on my dataset which includes **video and text** and I found the training pipeline a bit confusing. Can you please give a pointer on that (e.g., which file should I look for)?

**Comment by MAGAer13** [comment]
The video checkpoint is [here](https://huggingface.co/MAGAer13/mplug-owl-llama-7b-video) (It should work now), and if it is not work, see #101 for the checkpoint. Then you change the model in training pipeline by replacing `import mplug_owl` with `import mplug_owl_video` which replace the image model architecture with video model architecture.

**Comment by shaswati1** [comment]
@MAGAer13, which file should I look for the training pipeline?

**Comment by MAGAer13** [comment]
> @MAGAer13, which file should I look for the training pipeline itself?

See [train_it.sh](https://github.com/X-PLUG/mPLUG-Owl/blob/main/mPLUG-Owl/scripts/train_it.sh) and [./pipeline/train.py](https://github.com/X-PLUG/mPLUG-Owl/blob/main/mPLUG-Owl/pipeline/train.py)
