### ISSUE TITLE
about API

### ISSUE THREAD

**Issue by asige-yuan** [X-PLUG/mPLUG-Owl#96]
The API provided gives examples of images, What should I do if I'm using video?

**Comment by MAGAer13** [comment]
The API currently only support image only. If you want to treat the video as multiple images, just use multiple `<image>` as the placeholders for images.

**Comment by asige-yuan** [comment]
Thanks, Will a video version of the api be provided later？

**Comment by MAGAer13** [comment]
You can refer to the image API implementation, the API is just a wrapper of inference procedure.
