### ISSUE TITLE
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0

### ISSUE THREAD

**Issue by nullnameno** [X-PLUG/mPLUG-Owl#98]
Sorry, I encountered an issue while performing video inference, which is _**RuntimeError: probability tensor contains either 'inf', 'nan' or element<0**_. I am very curious about the reason for this error.

**Comment by MAGAer13** [comment]
Did you run this demo under bfloat16?

**Comment by MAGAer13** [comment]
Since the model is training under bfloat16, while the DepthwiseConv3D only support half, so we do the conversion from bf16 to half during Conv then we convert it back which leads to the unstable results.

**Comment by LinB203** [comment]
> Sorry, I encountered an issue while performing video inference, which is _**RuntimeError: probability tensor contains either 'inf', 'nan' or element<0**_. I am very curious about the reason for this error.

Same question and just use demo code.

**Comment by nullnameno** [comment]
> Did you run this demo under bfloat16?

Yes, I strictly followed the example you provided in README.md for video reasoning. I don't know why the model reported such an error.

**Comment by ff1Zzd** [comment]
Same error as well. Follow the demo code strictly

**Comment by ff1Zzd** [comment]
Hi I have also tried to use the model (with video weights) to inference an image input, however I am getting an output with **all special tokens**. I believe it might be caused by the same bug as the one raise by nullnameno. Here is the screenshot of the output.

<img width="930" alt="image" src="https://github.com/X-PLUG/mPLUG-Owl/assets/89125308/59bbccf3-8393-4737-8cc9-e2ec71cf2fdd">

**Comment by sdjhshbswp** [comment]
> Hi I have also tried to use the model (with video weights) to inference an image input, however I am getting an output with **all special tokens**. I believe it might be caused by the same bug as the one raised by nullnameno. Here is the screenshot of the output.
> 
> <img alt="image" width="930" src="https://user-images.githubusercontent.com/89125308/251342484-59bbccf3-8393-4737-8cc9-e2ec71cf2fdd.png">

I meet the same problem when I run the inference_video.py. I also get the res tensor of all zero.

**Comment by MAGAer13** [comment]
See #101
